name: Unit & Component Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  tests:
    name: Run unit tests and CT tests
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    env:
      VITE_APP_GIT_TAG: ${{github.ref}}
      VITE_APP_GIT_SHA: ${{github.sha}}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
